### ISSUE TITLE
UART port is not working 

### ISSUE THREAD

**Issue by huyhoang8398** [erazor83/pyRFM#2]
i tried /dev/ttyAMA0 in Rasp Pi 3 B+, but i got this error 
```
Traceback (most recent call last):
File "rf95_server.py", line 35, in
print('HW-Version: ', ll.getVersion())
File "../lib/ll/ll_rfm9x.py", line 220, in getVersion
return self.PL.readRegister(RFM_REG_VERSION)
File "../lib/pl/pl_serial_seed.py", line 67, in readRegister
return rx[0]
IndexError: list index out of range
```
i switched to an USB UART and it's working perfect
Why so?

**Comment by erazor83** [comment]
/dev/ttyAMA0 is not the device-name of the seed-interface...

**Comment by huyhoang8398** [comment]
sorry i forgot to close this issue, fixed with the right port name
